### ISSUE TITLE
CT Tried to insert a disposed Node

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#64] opened 2021-08-05 16:17 UTC
```
greenhouse-effect : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628136020808/phet-io-wrappers/state/?sim=greenhouse-effect&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1628136020808%22%2C%22timestamp%22%3A1628153064268%7D
Uncaught Error: Uncaught Error: Assertion failed: Tried to insert a disposed Node
Error: Assertion failed: Tried to insert a disposed Node
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628136020808/assert/js/assert.js:25:13)
at VBox.insertChild (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628136020808/scenery/js/nodes/Node.js:620:15)
at VBox.setChildren (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628136020808/scenery/js/nodes/Node.js:862:16)
at VBox.setChildren (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628136020808/scenery/js/nodes/LayoutBox.js:251:11)
at VBox.set children [as children] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628136020808/scenery/js/nodes/Node.js:892:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628136020808/scenery/js/nodes/Node.js:6791:23
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628136020808/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628136020808/sherpa/lib/lodash-4.17.4.js:9359:14)
at VBox.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628136020808/scenery/js/nodes/Node.js:6778:7)
at new LayoutBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628136020808/scenery/js/nodes/LayoutBox.js:106:10)
id: Bayes Chrome
Snapshot from 8/4/2021, 10:00:20 PM
```

**Comment by jbphet** [comment] 2021-08-06 17:41
This is easy to duplicate manually in the state wrapper.  Just do this:
 1. Open the state wrapper
 2. Go to the PhET menu (in the lower right) and bring up the "Options..." dialog
 3. Sit there a few seconds.

The problem is that the `createOptionsDialogContent` function that is provided to the `Sim` constructor in `greenhouse-effect-main` is returning a singleton instance, but somewhere in phet-io land that instance is getting disposed, so when the phet-io tries to recreate the state, it gets back a node on which `dispose` has been invoked.

**Comment by jbphet** [comment] 2021-08-06 20:33
The root cause of this problem is that I was using a singleton for the options dialog in the sim, and that singleton was getting disposed in the downstream sim in the state wrapper because it's in a PhetioCapsule.  @zepumph suggested that I make it dynamic instead and implement a proper dispose function on it, and also use the dynamic tandem passed in to the `createOptionsDialogContent` call.  This worked (though it took a while to get it all right).

I think this is fixed, closing.

**Closed by jbphet** 2021-08-06 20:33 UTC
Labels: type:automated-testing
