### ISSUE TITLE
VO mislabels checkbox for Layer 1 thermometer

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#385] opened 2024-01-30 21:52 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Safari 17.1.2

**Problem description**
For https://github.com/phetsims/qa/issues/1033, on the Layer Model Screen VO calls the Layer 1 thermometer checkbox, the Layer 2 thermometer checkbox. The other checkboxes are correctly labeled. 

**Steps to reproduce**
1. Turn on VO
2. On the Layer Model Screen tab to and increase the amount of Absorbing Layers by any amount
3. Tab to the Thermometer checkbox for Layer 1

**Visuals**
<img width="1440" alt="Screenshot 2024-01-30 at 4 41 34 PM" src="https://github.com/phetsims/greenhouse-effect/assets/87318828/266e70fc-6bbb-4ffa-ad78-9f7126be93c9">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.0-dev.3/phet/greenhouse-effect_all_phet.html
Version: 1.3.0-dev.3 2024-01-23 21:58:15 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15
Language: en-US
Window: 1356x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment] 2024-01-30 21:58
When the checkbox is checked or unchecked, VO correctly states that the thermometer has been added/removed from layer 1. 
<img width="1023" alt="Screenshot 2024-01-30 at 4 58 29 PM" src="https://github.com/phetsims/greenhouse-effect/assets/87318828/dda324e2-be32-4b54-82c9-bf959656e211">

**Comment by arouinfar** [comment] 2024-02-01 17:08
This is really bizarre @Nancy-Salpepi. I see the incorrect VO output in your first screenshot, but I am unable to reproduce it.

**Comment by Nancy-Salpepi** [comment] 2024-02-01 19:59
I think you should be able to reproduce if you follow these steps @arouinfar:
1. Go to the Layer Model Screen and turn on VO
2. Tab to the Absorbing layers and increase to 3
3. Tab to the Layer 1 Thermometer Checkbox and uncheck it
4. Tab back to the Absorbing layers and decrease back to 0 and then increase back to 1
5. Tab to the layer 1 Thermometer Checkbox

**Comment by Nancy-Salpepi** [comment] 2024-02-01 20:03
And if you follow these similar steps you get VO calling it the Energy Balance Checkbox:
1. Go to the Layer Model Screen and turn on VO
2. Tab to the Absorbing layers and increase to 1
3. Tab to the Layer 1 Thermometer Checkbox and uncheck it
4. Tab back to the Absorbing layers and decrease back to 0 and then increase back to 1
5. Tab to the layer 1 Thermometer Checkbox
<img width="1440" alt="Screenshot 2024-02-01 at 2 49 55 PM" src="https://github.com/phetsims/greenhouse-effect/assets/87318828/986c6ad4-eb1c-4baf-94fc-4e87e9818888">

**Comment by arouinfar** [comment] 2024-02-01 22:54
@Nancy-Salpepi I've been using VO on Safari, but I haven't been able to reproduce any of your examples.

Here's my troubleshooting info:
>Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.0-dev.3/phet/greenhouse-effect_en_phet.html
Version: 1.3.0-dev.3 2024-01-23 21:58:15 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1324x875
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by arouinfar** [comment] 2024-02-05 18:28
@Nancy-Salpepi and I paired on this, and it turns out we have different versions of macOS. I upgraded to the latest, and I am now able to reproduce.

**Comment by jbphet** [comment] 2024-02-06 23:26
I am unable to reproduce any part of this on Windows+NVDA.  This seems like a VoiceOver-specific problem.  @Nancy-Salpepi - can I request that you try it in the a11y view and see how what you're hearing relates to what you're seeing being selected in the PDOM at the right?  Here's a screenshot from my Windows machine to illustrate:

![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/5185c935-e6cd-4c91-947b-6ef7e1830d0b)

**Comment by Nancy-Salpepi** [comment] 2024-02-07 13:42
It is definitely a VO issue. The focus is on Layer 1 thermometer in the pdom but VO says layer 2:
<img width="1440" alt="Screenshot 2024-02-07 at 8 38 11 AM" src="https://github.com/phetsims/greenhouse-effect/assets/87318828/724f505c-3f1c-4e26-aa26-0291ffb3c856">

**Comment by jbphet** [comment] 2024-02-07 17:49
@jessegreenberg and I reviewed this, and he is going to try to duplicate with a simple HTML example to make sure it isn't something PhET-specific and to potentially report the problem to Apple.

**Comment by jbphet** [comment] 2024-02-07 17:50
@arouinfar - See the comment above.  Do we need to wait until there is some resolution on this, or can we proceed with interviews with the problem present?

**Comment by arouinfar** [comment] 2024-02-07 17:57
@jbphet I'd like to wait until @jessegreenberg determines if this is a PhET problem or an Apple problem. It's a fairly serious issue, so if it's something we can fix, I'd like to fix it before interviews.

**Comment by jessegreenberg** [comment] 2024-02-07 20:10
I couldn't reproduce this on macOS 11.7.6 + Safari, but it sounds like this is specific to a recent version of macOS.

@Nancy-Salpepi @arouinfar are you able produce this bug here? https://bayes.colorado.edu/dev/html/jg-tests/checkbox-test.html

**Comment by Nancy-Salpepi** [comment] 2024-02-07 20:53
I was not able to reproduce using the link above. 
In the sim, it has something to do with the visibility of the checkboxes and not just checking/unchecking them.

**Comment by jessegreenberg** [comment] 2024-02-07 21:00
I see, thanks @Nancy-Salpepi - I just read https://github.com/phetsims/greenhouse-effect/issues/385#issuecomment-1922131097 and https://github.com/phetsims/greenhouse-effect/issues/385#issuecomment-1922139063 more carefully. Ill make a new simple test.

**Comment by jessegreenberg** [comment] 2024-02-07 21:22
@Nancy-Salpepi or @arouinfar can you please try this one? In this simple demo there are buttons to add/remove checkboxes. If it happens here we know its related to the `hidden` attribute. If not, it could be something totally different about PhET's context and we will need to investigate more thoroughly.

https://bayes.colorado.edu/dev/html/jg-tests/checkbox-test.html

**Comment by Nancy-Salpepi** [comment] 2024-02-07 21:43
I wasn't able to reproduce with the new test. 😕

**Comment by jessegreenberg** [comment] 2024-02-07 22:05
Bummer! Alright, thanks for testing. Then it is not clear what is causing this yet. But that means there is a chance we can find out and fix it. There is a chance though that we will identify a macOS bug that is not fixable.

This is also definitely not specific to greenhouse, and probably happens in many sims.

I think to keep investigating this, I will need to debug on a Mac with the latest macOS.

**Comment by jessegreenberg** [comment] 2024-02-08 17:36
Since this impacts all sims I moved next steps to https://github.com/phetsims/scenery/issues/1606.

**Comment by arouinfar** [comment] 2024-02-08 17:57
Thanks @jessegreenberg! 

@jbphet this no longer blocks interviews.

**Comment by jessegreenberg** [comment] 2024-02-21 23:22
OK, a workaround for https://github.com/phetsims/scenery/issues/1606 has been committed and this should be fixed.

**Comment by arouinfar** [comment] 2024-02-23 21:40
Thanks @jessegreenberg! I am no longer able to reproduce in VO on main and in dev.6 (interview version). Closing.

**Closed by arouinfar** 2024-02-23 21:40 UTC
Labels: type:bug, dev:description
