### ISSUE TITLE
Play button says "unavailable"

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#405] opened 2024-05-06 17:45 UTC
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox + NVDA
**Problem description**
For https://github.com/phetsims/qa/issues/1080
When focusing on the play button it will read "play button unavailable." Clicking on it works as expected.

**Visuals**

https://github.com/phetsims/greenhouse-effect/assets/41024075/9f11f660-93a4-4f89-8f82-f1a3a5dff144

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.0-dev.11/phet/greenhouse-effect_all_phet.html
Version: 1.3.0-dev.11 2024-04-26 19:11:48 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0), or similar)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment] 2024-05-10 01:07
I've started doing some investigation on this, here are some notes:

- I can duplicate this on my Windows 11 machine, but only on Firefox, it does not occur on Chrome nor on Edge
- It happens when the button is in either the "Play" or "Paused" state
- If I start the sim with the Greenhouse-Effect-specific query parameter `initiallyStarted=true`, the problem does not occur.
- The thing that I think is supposed to cause NVDA to say that something is "unavailable" is `aria-disabled="true"` in the HTML.  This seems to work fine in Chrome (I tested it by going to the buttons without starting the sunlight).  I don't see that in the HTML when I inspect it, but I do see `aria-disabled="false"`, and there are old NVDA GitHub issues about this being handled incorrectly, see https://github.com/nvaccess/nvda/issues/3565.

At the moment, this seems more like a bug with the interaction between Firefox and NVDA than anything we're doing incorrectly, but I'll check in with @jessegreenberg and get his input, since he has done the most work in this arena.

**Comment by jessegreenberg** [comment] 2024-05-10 15:53
Thanks for looking into this @jbphet - the problem is happening for me too. I can see the problem in this simple HTML snippet

```html
<h1>Testing</h1>
<div id='div'>
  <button id='button'>Pause</button>
</div>

<script>
  const button = document.querySelector( 'button' );
  const div = document.querySelector( 'div' );

  window.setInterval( () => {
    const isDisabled = div.getAttribute( 'aria-disabled' ) === 'true';
    const newValue = isDisabled ? 'false' : 'true';
    div.setAttribute( 'aria-disabled', newValue );
  }, 5000 );
</script>
```

The problem goes away if the aria-disabled attribute is put on the button instead of the parent div. But we shouldn't have to do that. Something about the way Firefox updates when aria-disabled changes has broken. I think we should submit a bug report to mozilla and not spend time applying a workaround. @arouinfar are you OK with that?

**Comment by arouinfar** [comment] 2024-05-10 17:51
Sounds good @jessegreenberg. Let's proceed with a bug report and defer/close this issue.

**Comment by jessegreenberg** [comment] 2024-05-10 20:03
OK, thanks! I opened https://github.com/phetsims/a11y-research/issues/197 to track the bug report for Firefox. I added a note to the "accessibility-bugs.md" document until it is fixed. Closing.

**Closed by jessegreenberg** 2024-05-10 20:03 UTC
Labels: type:bug, dev:description
