### ISSUE TITLE
Layer Temperature Alert Order Varies [VO]

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#402] opened 2024-04-29 19:40 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
Safari 17.4.1

**Problem description**
For https://github.com/phetsims/qa/issues/1080, with VoiceOver on the Layer Model Screen, when the temperature is stable, the order of the temperature alerts varies. Most of the time, it is surface > Layer 3 >  Layer 1 > Layer 2 (which is odd). I have also gotten Surface > Layer 2 > Layer 1> Layer 3 and Surface > Layer 1 > Layer 3 > Layer 2. 

**Steps to reproduce**
1. Press Start Sunlight Button
2. Tab to Absorbing Layers and increase to 3 
3. Wait until the temperature is stable-- VO reads then out in the order: surface > Layer 3 >  Layer 1 > Layer 2 
4. Decrease the Layers to 2
5. Uncheck the Layer 2 Thermometer Checkbox
6. Increase the Layers back to 3
7. Check the Layer 2 Thermometer Checkbox
8. Wait until the temperature is stable-- VO reads then out in the order: surface > Layer 1 >  Layer 3 > Layer 2
 
**Visuals**
Videos start at the point of temperature stabilization. 

https://github.com/phetsims/greenhouse-effect/assets/87318828/d1ef7d8c-e633-4f98-b423-f8493d685212

https://github.com/phetsims/greenhouse-effect/assets/87318828/3db8d727-53e3-4f7b-9704-ab47ccefd999

**Comment by arouinfar** [comment] 2024-04-29 21:06
Thanks for reporting @Nancy-Salpepi. 

Stating the Layer temperatures in varying orders makes it more difficult to understand. If the order is something we can control, it would make more sense to state the surface temperature followed by the layer temperatures in ascending order (if present/checked).

**Comment by jbphet** [comment] 2024-05-03 22:04
I understand the problem, and can duplicate it locally on my Win 11 machine using the a11y page.  It would not be trivial to change the order, though it isn't impossible.  Right now, the temperature is announced when the layer becomes stable, meaning that the layer's temperature is changing at a rate lower than an empirically determined threshold.  This occurs for the different layers at different times due to the nature of the model, and I'm not at all sure how to change the model to improve this.  Another possible way to address this would be to implement something like a delay queue that waits for some amount of time, reorders messages that come in during the delay interval, and then sends them out in order.  I ran a test to see what kind of temporal variation is occurring, and saw a range of 160 ms to 1.25 sec between back-to-back layer temperature alerts, though this was not a very extensive test.  Based on this, I'm thinking that we would need to queue and thus delay these alerts for at least 1.5 seconds to effectively reorder them in most cases.

I'd estimate a full day of my time to implement and unit test this.

Assigning to @arouinfar to make a call on whether it's worth the delay to the messages and the development time.

**Comment by arouinfar** [comment] 2024-05-03 22:13
Thanks for investigating @jbphet. It's good to understand why the alerts are triggered in the order that they are. I do not think the issue is severe enough to warrant major changes such as you describe, so I'll close this as wont-fix.

**Closed by arouinfar** 2024-05-03 22:13 UTC
Labels: type:bug, dev:description
