### ISSUE TITLE
VO interrupts scene description, Greenhouse levels, and other alerts

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#254] opened 2023-01-06 20:23 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 13.0.1

**Browser**
safari 16.1

**Problem description**
For https://github.com/phetsims/qa/issues/871, on the Waves Screen when switching between years, VO skips over the scene description, greenhouse concentration level and other alerts. 
Many alerts are also skipped when increasing/decreasing the Greenhouse gas concentration levels. 

**Steps to reproduce**
1. Turn on VO
2. Tab to and Press Start Sunlight button
3. Tab to Greenhouse Gas Concentration panel and switch to years (or you can keep on concentration)
4. Shift + Tab to the Year radio buttons and change to another year. 

Noting that I am seeing these interruptions with VO in general (just saw this same thing with Friction). Mobile VO doesn't behave this way. 
Also noting that I didn't see these interruptions when I was testing in the past for the version @arouinfar was using for interviews.

**Visuals**

https://user-images.githubusercontent.com/87318828/211093030-d6ebaac4-47d5-4357-95f0-ceae49f0327e.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html?
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
Language: en-US
Window: 1399x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment] 2023-01-07 00:28
We have very coarse control over this unfortunately. It doesn't look like we are using assertive alerts anywhere in this sim so we are doing what we can to request that these are not interrupted.

> Also noting that I didn't see these interruptions when I was testing in the past for the version

It is possible something in PhET code changed but also possible that VO changed since then. It would be good to verify that this is not happening in the older sim version on the same platform.

But it looks like work on this has been deferred for now, so removing my assignment. Please reassign if I can help when work continues.

**Comment by jbphet** [comment] 2023-01-11 00:09
@Nancy-Salpepi - Can you please check if the behavior that you describe above is different that the behavior in https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.3-rc.1/ (the previous prototype release)?  This would help us to figure out next steps.

**Comment by Nancy-Salpepi** [comment] 2023-01-11 13:57
@jbphet. @arouinfar, and @jessegreenberg -- this seems to be an issue with the newest version of VO. Alerts used to pile up, but now they get interrupted (too much).  I am testing on macOS 13.1 and safari 16.1.

There wasn't anything in the folder you provided above. I went back to last version I tested from https://github.com/phetsims/qa/issues/825 where I know things were working pretty well and I am seeing the same problem.
 
In 1.1.0-dev.12, when changing the concentration slider, out of the 3 key statements I was supposed to hear--(1) more/less IR redirecting back to surface, (2)surface temperature warming/cooling, now X Kelvin, and (3)more/less IR emitting from surface-- I only hear the second one. 
When switching between time periods, the scene description and the greenhouse gas levels comparison between time periods are skipped. I hear 2/3 of the key statements, but which I hear varies. 

Using iPadOS 16.1.1 and safari, mobile VO is working nicely with 1.1.0-rc.1.

**Comment by jessegreenberg** [comment] 2023-01-11 15:01
@Nancy-Salpepi can you please try VoiceOver in Chrome and see if the issue is happening there? It could be an issue with Safari.

**Comment by Nancy-Salpepi** [comment] 2023-01-11 15:49
@jessegreenberg it is the same with Chrome.

**Comment by jessegreenberg** [comment] 2023-01-11 15:59
OK, that's helpful to know, thanks.

**Comment by jbphet** [comment] 2023-01-13 23:07
It looks like there isn't anything actionable on this for the 1.1 release of Greenhouse Effect, or even for the code on master.  @arouinfar and @jessegreenberg - do you agree with this assessment and can this be closed?

**Comment by jessegreenberg** [comment] 2023-01-13 23:16
I made a general issue for this because it impacts all sims. This week @terracoda reached out to Apple about a different but similar (possibly even related) bug and they actually responded. I think there is a chance Apple could fix this in an update.

Fine with me to close since it is beyond this sim.

**Comment by jbphet** [comment] 2023-01-13 23:52
Thanks @jessegreenberg.  Closing.

**Closed by jbphet** 2023-01-13 23:52 UTC
Labels: type:bug, dev:description
