### ISSUE TITLE
Energy Balance is read out incorrectly if sim has not yet sarted

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#176] opened 2022-06-14 20:13 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/811
If you turn on the Energy Balance graph before you start the sunlight in the sim, an alert will play saying there is a net inflow of energy. This is true once you start the sunlight, but before then the graph is blank and there is no information available as no actions are happening yet.

**Visuals**
<img width="475" alt="basealertwrong" src="https://user-images.githubusercontent.com/41024075/173680201-119d5343-1291-42d9-bf30-557798c79d2a.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.9/phet/greenhouse-effect_en_phet.html?screens=1&postMessageOnLoad&postMessageOnError&supportsInteractiveDescription=true
Version: 1.1.0-dev.9 2022-06-08 20:37:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment] 2022-06-14 20:39
What's worse, is the scene description describes the opposite from the alerts:
<img width="922" alt="opposite" src="https://user-images.githubusercontent.com/41024075/173684378-0c3d2900-34fb-454b-bd32-ad437135079d.png">

**Comment by jbphet** [comment] 2022-07-01 19:20
I have this mostly working as desired, but while testing it I ran into one odd and hard-to-reproduce case.  Here is the sequence needed to reproduce.  The timing matters, so read through it before doing it if you intend to try it.

- Load the sim in the a11y view and go to the Waves screen
- Start the sunlight
- Hit the Reset All button and then very quickly re-enable the energy balance indicator
- Continue cycling through the process of starting sunlight, reset, quickly re-enabling energy balance, and eventually you'll see a description of the energy balance come out before the sun is shining.  It will look something like this:

![image](https://user-images.githubusercontent.com/3082831/176956117-00342a46-9cbd-42fe-a1e0-32c077d86bfc.png)

There are other, similar scenarios that can be created, but this is one of the easiest to reproduce.

After looking through the code, I think what's going on here is that the `GasConcentrationAlerter` is stateful, but it's state isn't getting reset with the rest of the sim.  It also updates its internal state at 4 second intervals whether the sun is shining or not.  So, if you happen to reset the screen and then re-enable the energy balance indicator inside one of those 4 second windows, it will use the previous energy balance to decide whether to log an alert.

I think the best solution to this is probably to reset `GasConcentrationAlerter` when the model is reset.

**Comment by jbphet** [comment] 2022-07-01 19:46
@jessegreenberg - I think I have this working, but I'd like you to take a look at the changes before the next steps.  My biggest question is about resetting the concentration describer.  To fix the problem described in the previous comment, I ended up wiring through a way to reset the `GasConcentrationDescriber`.  It seemed reasonable me, but I'm fairly new to description, so I want to make sure this approach is copacetic.

If this seems good, please assign to @arouinfar and @Matthew-Moore240 to review the behavior.

**Comment by jessegreenberg** [comment] 2022-07-01 21:24
Ah, that makes sense with this approach. Thanks for catching/adding.

Should these "previous" value variables be reset here as well or were they intentionally excluded?

`previousTemperature`
`previousOutgoingEnergy`

**Comment by jbphet** [comment] 2022-07-05 23:19
Thanks @jessegreenberg - I've added those to the reset method.

**Comment by jbphet** [comment] 2022-07-05 23:22
@arouinfar - Please check the behavior and make sure that it is what we want based on [the design team discussion](https://github.com/phetsims/greenhouse-effect/issues/176#issuecomment-1163534006) above.  If so, this can be closed.

**Comment by arouinfar** [comment] 2022-07-06 20:15
Looks good, thanks @jbphet

**Comment by jbphet** [comment] 2022-07-08 18:25
Reopening, since I thought it would be good to have QA double check this during a dev test that is currently being set up.

**Closed** 2022-07-13 22:11 UTC
Labels: type:bug, status:ready-for-review
